version: "3.8"

services:
  frontend-dev:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ../src:/app/src
      - ../.vscode:/app/.vscode
      - ../.gitignore:/app/.gitignore
      - ../.pretterrc.cjs:/app/.pretterrc.cjs
      - ../.eslintrc.cjs:/app/.eslintrc.cjs
      - ../index.html:/app/index.html
      - ../package.json:/app/package.json
      - ../tsconfig.json:/app/tsconfig.json
      - ../tsconfig.node.json:/app/tsconfig.node.json
      - ../vit.config.ts:/app/vit.config.ts
      - ../public:/app/public
      - ../.storybook:/app/.storybook
      - ../.git:/app/.git